accessing
hasError: anObject
	hasError := anObject